name: Tunshell

on: 
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tunshell
      run: wget https://lets.tunshell.com/init.sh -O - 2> /dev/null | sh -s -- T Utc8VH5v99lk7mNqvZyaNX MsPexMbW3aNUXNeu9CaHpf
